# variables
name: GenAI Arcade
description:  DRAFT - This is a project from the QUT GenAI Lab, called the GenAI Arcade
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
title: GenAI Arcade
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    *DRAFT* This is a project from the QUT GenAI Lab, called the GenAI Arcade
baseurl: "https://www.genai-arcade.net" # the subpath of your site, e.g. /blog
permalink: /:year:month:day/:title
url: # "http://willsh97.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed